<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="background-color: #212121;">
    Value	State	Description
0	UNSENT	Client has been created. open() not called yet.
1	OPENED	open() has been called.
2	HEADERS_RECEIVED	send() has been called, and headers and status are available.
3	LOADING	Downloading; responseText holds partial data.
4	DONE	The operation is complete.
</body>
<script>
    const requestUrl = 'https://api.github.com/users/hiteshchoudhary'
    const xhr = new XMLHttpRequest();
    xhr.open('GET', requestUrl)  // for one time tracking
    xhr.onreadystatechange = function () {
        console.log(xhr.readyState);
        if(xhr.readyState === 4){
            // const data = this.responseText
            // console.log(data);   // data of this api https://api.github.com/users/hiteshchoudhary
            // console.log(typeof data);  // string 
            // console.log(data.follower);  // undefined
            const data = JSON.parse(this.responseText)
            console.log(data);   // data of this api https://api.github.com/users/hiteshchoudhary
            console.log(typeof data);  // object
            console.log(data.followers); // 16658
        }
    }
    // console.log(xhr.readyState);
    xhr.send();
</script>
</html>



<!-- Value	State	Description
0	UNSENT	Client has been created. open() not called yet.
1	OPENED	open() has been called.
2	HEADERS_RECEIVED	send() has been called, and headers and status are available.
3	LOADING	Downloading; responseText holds partial data.
4	DONE	The operation is complete. -->

<!-- The global fetch() method starts the process of fetching a resource from the network, returning a promise that is fulfilled once the response is available. -->
<!-- The promise resolves to the Response object representing the response to your request.
A fetch() promise only rejects when a network error is encountered (which is usually when there's a permissions issue or similar). 
A fetch() promise does not reject on HTTP errors (404, etc.). Instead, a then() handler must check the Response.ok and/or Response.status properties. -->